### ISSUE TITLE
Unit mesure for percentage

### ISSUE THREAD

**Issue by sstraus** [lorenwest/node-red-contrib-state#17]
Hi, what is the expected unit measure for the percentage? Like humidity?
I can't find any suitable one on the list, but it should be common in nodered.

thanks

**Comment by lorenwest** [comment]
The units functionality exists for conversion purposes.  It uses the [convert-units](https://www.npmjs.com/package/convert-units) library to allow unit conversion within a category.

Data typing is optional, and you wouldn't need it for percentages because there aren't other units to convert to/from.
